[[pubs]]
title = "Spontaneous Particle Creation by Oscillating Compact Stars"
authors = ["Adrián del Río", "Pau López-Oliver"]
journal = "Physical Review D"
month = "May"
year = 2026
doi = "10.1103/9s47-zspb"
link = "https://doi.org/10.1103/9s47-zspb"
arxiv_link = "https://arxiv.org/abs/2602.20253"
selected = true

[[pubs]]
title = "Typst: A Modern Typesetting Engine for Science"
authors = ["Andrey Voynov", "Alberto Corbi", "Pau López-Oliver", "David Gil"]
journal = "International Journal of Interactive Multimedia and Artificial Intelligence"
month = "Feb"
year = 2026
doi = "10.9781/ijimai.2026.2269"
selected = false